In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
return_df = pd.read_csv(r"D:\flipkart_data\return_reports.csv")

In [3]:
return_df.head()

,Product Id,SKU ID,Category,Brand,Vertical,Order Date,Fulfillment Type,Return Amount,Reason,Sub Reason,Is Replacement,Return Type,Return Units,Location Id
0,CFTGDDBYMAZQCQ8X,WEEGRO-CT-M1,LivingRoomSF,WEEGRO,SmallCoffeeTables,2026-05-09,NON_FBF,1838,MFG DEFECT POOR FINISH,WOOD LAMINATE SCRATCHES,False,customer_return,1,LOC419174c836c04122a33548631d5d7801
1,CFTGDDBYMAZQCQ8X,WEEGRO-CT-M1,LivingRoomSF,WEEGRO,SmallCoffeeTables,2026-05-12,NON_FBF,1838,DAMAGED PRODUCT,DAMAGED PRODUCT RECEIVED,False,customer_return,1,LOC419174c836c04122a33548631d5d7801
2,CFTHGMJZGMGDGXZC,WEEGRO-CT-PLASTIC,LivingRoomSF,WEEGRO,SmallCoffeeTables,2026-05-06,NON_FBF,953,INSTALL ASSEMBLY ISSUE,ALIGNMENT ISSUE,False,customer_return,1,LOC419174c836c04122a33548631d5d7801
3,CFTGYFNVWDUHNJFW,WEEGRO-CT-PL,LivingRoomLF,WEEGRO,CoffeeAndCentreTable,2026-05-20,NON_FBF,2134,MFG DEFECT POOR FINISH,WOOD LAMINATE SCRATCHES,False,customer_return,1,LOC419174c836c04122a33548631d5d7801
4,CFTGDDBYMAZQCQ8X,WEEGRO-CT-M1,LivingRoomSF,WEEGRO,SmallCoffeeTables,2026-05-20,NON_FBF,2171,MFG DEFECT POOR FINISH,NOT FUNCTIONING,False,customer_return,1,LOC419174c836c04122a33548631d5d7801

In [4]:
return_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product Id        7 non-null      object
 1   SKU ID            7 non-null      object
 2   Category          7 non-null      object
 3   Brand             7 non-null      object
 4   Vertical          7 non-null      object
 5   Order Date        7 non-null      object
 6   Fulfillment Type  7 non-null      object
 7   Return Amount     7 non-null      int64
 8   Reason            7 non-null      object
 9   Sub Reason        7 non-null      object
 10  Is Replacement    7 non-null      bool
 11  Return Type       7 non-null      object
 12  Return Units      7 non-null      int64
 13  Location Id       7 non-null      object
dtypes: bool(1), int64(2), object(11)
memory usage: 867.0+ bytes

In [5]:
return_df.shape

(7, 14)

In [6]:

return_df.isnull().sum()

Product Id          0
SKU ID              0
Category            0
Brand               0
Vertical            0
Order Date          0
Fulfillment Type    0
Return Amount       0
Reason              0
Sub Reason          0
Is Replacement      0
Return Type         0
Return Units        0
Location Id         0
dtype: int64

In [7]:
return_df.rename(columns={
    'Product Id':'product_id',
    'SKU ID':'sku',
    'Category':'category',
    'Brand':'brand',
    'Vertical':'vertical',
    'Order Date':'order_date',
    'Fulfillment Type':'fulfillment_type',
    'Return Amount':'return_amount',
    'Reason':'reason',
    'Sub Reason':'sub_reason',
    'Is Replacement':'is_replacement',
    'Return Type':'return_type',
    'Return Units':'return_units',
    'Location Id':'location_id'
}, inplace=True)

In [8]:
return_df['order_date']=pd.to_datetime(return_df['order_date'])

In [9]:
return_df.duplicated().sum()

np.int64(0)

In [10]:
return_df.describe()

                order_date  return_amount  return_units
count                    7       7.000000           7.0
mean   2026-05-16 00:00:00    1542.000000           1.0
min    2026-05-06 00:00:00     923.000000           1.0
25%    2026-05-10 12:00:00     945.000000           1.0
50%    2026-05-20 00:00:00    1838.000000           1.0
75%    2026-05-20 00:00:00    1986.000000           1.0
max    2026-05-25 00:00:00    2171.000000           1.0
std                    NaN     579.862627           0.0

In [11]:
return_df.nunique()

product_id          3
sku                 3
category            2
brand               1
vertical            2
order_date          5
fulfillment_type    1
return_amount       6
reason              3
sub_reason          4
is_replacement      1
return_type         1
return_units        1
location_id         1
dtype: int64

In [12]:

return_df.drop(columns=[
    'brand',
    'fulfillment_type',
    'return_type',
    'return_units',
    'location_id',
    'is_replacement'
], inplace=True, errors='ignore')

->brand column is removed because all product belongs to weegro
->fulfillment is non-fbf
->return is done by only customers
->all customer returned only one unit which they purchased
->returned to the same location id(seller) by all customers
->customers did not opt for replacement

In [13]:
return_df.to_csv(
    r"D:\flipkart_data\data\cleaned\cleaned_reports_data.csv",
    index=False
)

PermissionError: [Errno 13] Permission denied: 'D:\\flipkart_data\\data\\cleaned\\cleaned_reports_data.csv'

In [16]:
from sqlalchemy import create_engine
import pandas as pd
username="postgres"
password="irfan123"
host="localhost"
port="5432"
database="sales_analysis"
engine=create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")
table_name="returns"
return_df.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into the table '{table_name}' in database '{database}'.")

Data successfully loaded into the table 'returns' in database 'sales_analysis'.