In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [3]:
cancellation_df = pd.read_csv(r"D:\flipkart_data\cancellation_reports.csv")

In [4]:
cancellation_df.head()

,Product Id,SKU ID,Category,Brand,Vertical,Approved Date,Fulfillment Type,Cancellation Amount,Reason,Sub Reason,Is Courier Return,Cancellation Type,Cancellation Units,Location Id
0,CFTGDDBYMAZQCQ8X,WEEGRO-CT-M1,LivingRoomSF,WEEGRO,SmallCoffeeTables,2026-05-08,NON_FBF,1837.0,cancellation requested,mind changed,False,Customer,1,LOC419174c836c04122a33548631d5d7801
1,CFTGDDBYMAZQCQ8X,WEEGRO-CT-M1,LivingRoomSF,WEEGRO,SmallCoffeeTables,2026-05-08,NON_FBF,1838.0,cancellation requested,mind changed,False,Customer,1,LOC419174c836c04122a33548631d5d7801
2,CFTHGMJZGMGDGXZC,WEEGRO-CT-PLASTIC,LivingRoomSF,WEEGRO,SmallCoffeeTables,2026-05-08,NON_FBF,945.0,Seller did not handover,Seller did not handover,True,MarketPlace,1,LOC419174c836c04122a33548631d5d7801
3,CFTHGMJZGMGDGXZC,WEEGRO-CT-PLASTIC,LivingRoomSF,WEEGRO,SmallCoffeeTables,2026-05-08,NON_FBF,953.0,cancellation requested,delivery time long,False,Customer,1,LOC419174c836c04122a33548631d5d7801
4,CFTHGMJZGMGDGXZC,WEEGRO-CT-PLASTIC,LivingRoomSF,WEEGRO,SmallCoffeeTables,2026-05-12,NON_FBF,953.0,Other State Misroute,Other State Misroute,True,MarketPlace,1,LOC419174c836c04122a33548631d5d7801

In [5]:
cancellation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product Id           15 non-null     object
 1   SKU ID               15 non-null     object
 2   Category             15 non-null     object
 3   Brand                15 non-null     object
 4   Vertical             15 non-null     object
 5   Approved Date        15 non-null     object
 6   Fulfillment Type     15 non-null     object
 7   Cancellation Amount  15 non-null     float64
 8   Reason               15 non-null     object
 9   Sub Reason           15 non-null     object
 10  Is Courier Return    15 non-null     bool
 11  Cancellation Type    15 non-null     object
 12  Cancellation Units   15 non-null     int64
 13  Location Id          15 non-null     object
dtypes: bool(1), float64(1), int64(1), object(11)
memory usage: 1.7+ KB

In [6]:
cancellation_df.isnull().sum()

Product Id             0
SKU ID                 0
Category               0
Brand                  0
Vertical               0
Approved Date          0
Fulfillment Type       0
Cancellation Amount    0
Reason                 0
Sub Reason             0
Is Courier Return      0
Cancellation Type      0
Cancellation Units     0
Location Id            0
dtype: int64

In [7]:
cancellation_df['Approved Date']=pd.to_datetime(cancellation_df['Approved Date'])

In [8]:
cancellation_df.duplicated().sum()

np.int64(0)

In [9]:
cancellation_df.describe()

             Approved Date  Cancellation Amount  Cancellation Units
count                   15            15.000000           15.000000
mean   2026-05-11 08:00:00          1545.200000            1.066667
min    2026-05-01 00:00:00           945.000000            1.000000
25%    2026-05-06 00:00:00           957.500000            1.000000
50%    2026-05-08 00:00:00          1835.000000            1.000000
75%    2026-05-13 00:00:00          1838.000000            1.000000
max    2026-05-30 00:00:00          2337.000000            2.000000
std                    NaN           519.869242            0.258199

In [10]:
cancellation_df.nunique()

Product Id              3
SKU ID                  3
Category                2
Brand                   1
Vertical                2
Approved Date          10
Fulfillment Type        1
Cancellation Amount    10
Reason                  6
Sub Reason              8
Is Courier Return       2
Cancellation Type       2
Cancellation Units      2
Location Id             1
dtype: int64

In [11]:
cancellation_clean=cancellation_df[
    ['Product Id',
    'SKU ID',
    'Category',
    'Vertical',
    'Approved Date',
    'Cancellation Amount',
    'Reason',
    'Sub Reason',
    'Is Courier Return',
    'Cancellation Type',
    'Cancellation Units'
    ]].copy()

In [12]:
cancellation_clean.rename(columns={
    'Product Id':'product_id',
    'SKU ID':'sku',
    'Category':'category',
    'Vertical':'vertical',
    'Approved Date':'Approved Date',
    'Fulfillment Type':'fulfillment_type',
    'Cancellation Amount':'cancellation_amount',
    'Reason':'reason',
    'Sub Reason':'sub_reason',
    'Is Courier Return':'Is Courier Return',
    'Cancellation Type':'cancellation_type',
    'Cancellation Units':'cancellation_units',
}, inplace=True)

Brand,Fullfilment type,location Id are removed

In [13]:
cancellation_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           15 non-null     object
 1   sku                  15 non-null     object
 2   category             15 non-null     object
 3   vertical             15 non-null     object
 4   Approved Date        15 non-null     datetime64[ns]
 5   cancellation_amount  15 non-null     float64
 6   reason               15 non-null     object
 7   sub_reason           15 non-null     object
 8   Is Courier Return    15 non-null     bool
 9   cancellation_type    15 non-null     object
 10  cancellation_units   15 non-null     int64
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(7)
memory usage: 1.3+ KB

In [14]:
cancellation_clean.to_csv(
    r"D:\flipkart_data\data\cleaned\cleaned_cancellation_reports.csv",
    index=False
)

PermissionError: [Errno 13] Permission denied: 'D:\\flipkart_data\\data\\cleaned\\cleaned_cancellation_reports.csv'

In [15]:
from sqlalchemy import create_engine
import pandas as pd
username="postgres"
password="irfan123"
host="localhost"
port="5432"
database="sales_analysis"
engine=create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")
table_name="cancel"
cancellation_clean.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into the table '{table_name}' in database '{database}'.")

Data successfully loaded into the table 'cancel' in database 'sales_analysis'.